#!/bin/sh /etc/rc.common
START=70
USE_PROCD=1
PROG=/usr/sbin/ha-vrrp-autosync

start_service() {
  local en="$(uci -q get ha_vrrp.core.auto_sync || echo 0)"
  [ "$en" = "1" ] || return 0
  procd_open_instance
  procd_set_param command "$PROG" -f
  procd_set_param respawn 5 10 0
  procd_close_instance
}
