include $(TOPDIR)/rules.mk
PKG_NAME:=luci-app-ha-vrrp
PKG_VERSION:=0.5.8
PKG_RELEASE:=1
PKG_LICENSE:=MIT
LUCI_TITLE:=LuCI app for HA VRRP (Keepalived)
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+luci +ha-vrrp
include $(TOPDIR)/feeds/luci/luci.mk
