#!/bin/sh
set -e
echo '[ha-vrrp examples] applying configuration...'
uci set ha_vrrp.core.enabled='1'
uci set ha_vrrp.core.cluster_name='lab-ha'
uci set ha_vrrp.core.auth_pass='changeme-please'
uci set ha_vrrp.core.peer_host='192.168.254.1'
uci set ha_vrrp.core.peer_user='root'
uci set ha_vrrp.core.peer_port='22'
uci -q del_list ha_vrrp.core.sync_path '/etc/config/ha_vrrp'
uci -q del_list ha_vrrp.core.sync_path '/etc/config/network'
uci -q del_list ha_vrrp.core.sync_path '/etc/config/firewall'
uci add_list ha_vrrp.core.sync_path='/etc/config/ha_vrrp'
uci add_list ha_vrrp.core.sync_path='/etc/config/network'
uci add_list ha_vrrp.core.sync_path='/etc/config/firewall'
uci set ha_vrrp.core.auto_sync='1'
uci set ha_vrrp.core.auto_sync_interval='7'
uci set ha_vrrp.core.discover_cidr='192.168.254.0/24'
uci set ha_vrrp.core.discover_min='1'
uci set ha_vrrp.core.discover_max='10'
uci -q del_list ha_vrrp.core.health_wan_if 'wan'
uci add_list ha_vrrp.core.health_wan_if='wan'
uci set ha_vrrp.core.health_interval='2'
uci set ha_vrrp.core.health_fall='2'
uci set ha_vrrp.core.health_rise='2'
uci set ha_vrrp.core.health_weight='-30'
uci set ha_vrrp.core.health6_interval='3'
uci set ha_vrrp.core.health6_fall='2'
uci set ha_vrrp.core.health6_rise='2'
uci set ha_vrrp.core.health6_weight='-20'
uci -q delete ha_vrrp.inst_hb
uci set ha_vrrp.inst_hb='instance'
uci set ha_vrrp.inst_hb.name='HEARTBEAT'
uci set ha_vrrp.inst_hb.vrid='43'
uci set ha_vrrp.inst_hb.priority='100'
uci set ha_vrrp.inst_hb.state='BACKUP'
uci set ha_vrrp.inst_hb.preempt='1'
uci set ha_vrrp.inst_hb.iface='eth0'
uci set ha_vrrp.inst_hb.use_vlan='1'
uci set ha_vrrp.inst_hb.vlan_id='200'
uci set ha_vrrp.inst_hb.vip_cidr='192.168.254.254/24'
uci set ha_vrrp.inst_hb.unicast_src_ip='192.168.254.2'
uci -q del_list ha_vrrp.inst_hb.unicast_peer
uci add_list ha_vrrp.inst_hb.unicast_peer='192.168.254.1'
uci -q delete ha_vrrp.inst_admin
uci set ha_vrrp.inst_admin='instance'
uci set ha_vrrp.inst_admin.name='ADMINLAN'
uci set ha_vrrp.inst_admin.vrid='41'
uci set ha_vrrp.inst_admin.priority='100'
uci set ha_vrrp.inst_admin.state='BACKUP'
uci set ha_vrrp.inst_admin.preempt='1'
uci set ha_vrrp.inst_admin.iface='ADMINLAN'
uci set ha_vrrp.inst_admin.vip_cidr='192.168.1.254/24'
uci set ha_vrrp.inst_admin.unicast_src_ip='192.168.1.2'
uci -q del_list ha_vrrp.inst_admin.unicast_peer
uci add_list ha_vrrp.inst_admin.unicast_peer='192.168.1.1'
uci -q delete ha_vrrp.inst_gast
uci set ha_vrrp.inst_gast='instance'
uci set ha_vrrp.inst_gast.name='GAST'
uci set ha_vrrp.inst_gast.vrid='42'
uci set ha_vrrp.inst_gast.priority='100'
uci set ha_vrrp.inst_gast.state='BACKUP'
uci set ha_vrrp.inst_gast.preempt='1'
uci set ha_vrrp.inst_gast.iface='GAST'
uci set ha_vrrp.inst_gast.vip_cidr='192.168.4.254/24'
uci set ha_vrrp.inst_gast.unicast_src_ip='192.168.4.2'
uci -q del_list ha_vrrp.inst_gast.unicast_peer
uci add_list ha_vrrp.inst_gast.unicast_peer='192.168.4.1'
uci commit ha_vrrp
/usr/sbin/ha-vrrp-apply
/etc/init.d/keepalived restart || true
/etc/init.d/ha-vrrp enable
/etc/init.d/ha-vrrp restart
echo '[ha-vrrp examples] done.'
